# mklogo.py PNG SIZE OUT: turn the logo's alpha into a C mask for the graphical boot screen
import subprocess, sys
png, size, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]
raw = subprocess.check_output(["magick", png, "-background", "none", "-alpha", "extract", "-depth", "8", "gray:-"])
assert len(raw) == size * size, len(raw)
with open(out, "w") as f:
    f.write(f"// generated by tools/mklogo.py from tools/pd-boot-logo.png at {size}x{size}, the boot logo's alpha mask\n")
    f.write("#pragma once\n\n")
    f.write(f"#define PD_LOGO_SIZE {size}\n\n")
    f.write("static const unsigned char pd_logo_alpha[PD_LOGO_SIZE * PD_LOGO_SIZE] = {\n")
    for i in range(0, len(raw), 24):
        f.write("  " + ", ".join(str(b) for b in raw[i:i+24]) + ",\n")
    f.write("};\n")
